CREATE DATABASE QLBXTG

USE QLBXTG

CREATE TABLE KHACHHANG
(
	MAKH CHAR(10),
	TENKH VARCHAR(40),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(50),
	CMND VARCHAR(12),
	constraint PK_KH primary key (MAKH),
)

CREATE TABLE LOAIXE
(
	MALX CHAR(10),
	TENLX VARCHAR(40),
	CONGNGHE VARCHAR(40),
	constraint PK_LX primary key (MALX),
)

CREATE TABLE XEMAY
(
	MAXM CHAR(10),
	TENXM VARCHAR(40),
	MALX CHAR(10),
	NAMSX SMALLDATETIME,
	TRONGLUONG INT,
	GIA MONEY,
	constraint PK_XM primary key (MAXM),
)

CREATE LOAIHINHTG
(
	MALH VARCHAR(10),
	TENLH VARCHAR(40),
	PHANTRAMTT VARCHAR(5),
	KYHAN SMALLDATETIME,

)